sudo: required

language: python

services:
  - docker

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then docker build -t sjsclient_ft -f ci/Dockerfile.test .
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then docker run -d sjsclient_ft /bin/sh -c "cd /root/spark-jobserver; ./start.sh;"
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then docker ps -a
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then docker run sjsclient_ft /bin/sh -c "cd /root/spark-jobserver; tox -e functional_py35"  
install:
  - pip install tox-travis
  - pip install coveralls
script:
  - tox
  - tox -e cover
  - tox -e pep8
  - tox -e docs
after_success:
  coveralls
